import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";


export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title> Ditto </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
      <div className={styles.hero}>

      <div class="jumbotron">
        <h1 class="display-4">Welcome to Ditto!</h1>
        <p class="lead">
        Status:{" "}
          <code className={styles.code}>
            {!props.isLoggedIn && " Not"} Logged In
          </code>
        </p>
        <hr class="my-4"/>
        <p>Hi there, I am your personal assistant to help you plan your wedding! You can create your wedding plan, and modify it whenever you have to.
          <br/> You can check on the weather of the wedding venue as well, so you can be well prepared. Either way, it will be fun and I am here so you can have an easy experience!
        </p>
        <div className={styles.grid}>
          {props.isLoggedIn ? (
            <>
              <Link href="/dashboard" class="btn btn-warning btn-lg">
                <h5>Dashboard &rarr;</h5>
              </Link>
              <div
                onClick={logout}
                style={{ cursor: "pointer" }}
                class="btn btn-danger btn-lg"
              >
                <h5>Logout &rarr;</h5>
              </div>
            </>
          ) : (
            <>
              <Link href="/login" class="btn btn-warning btn-lg">
                <h5> Login &rarr;</h5>
              </Link>

              <Link href="/signup" class="btn btn-warning btn-lg">
                <h5> Sign Up &rarr;</h5>
              </Link>
            </>
          )}
        </div>
      </div>

      </div>


        


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
